## --- Importing data ---

In [24]:
import pandas as pd

df = pd.read_csv('data.csv')
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
4,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
246,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False
247,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False
248,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True
249,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
250,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False

## --- Listing out the columns ---

In [25]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

## --- Listing out row values by columns ---

In [26]:
df[['#', 'Name', 'Type 1', 'Type 2']]

       #        Name   Type 1  Type 2
0      1   Bulbasaur    Grass  Poison
1      2     Ivysaur    Grass  Poison
2      3    Venusaur    Grass  Poison
3      4  Charmander     Fire     NaN
4      5  Charmeleon     Fire     NaN
..   ...         ...      ...     ...
246  247     Pupitar     Rock  Ground
247  248   Tyranitar     Rock    Dark
248  249       Lugia  Psychic  Flying
249  250       Ho-oh     Fire  Flying
250  251      Celebi  Psychic   Grass

[251 rows x 4 columns]

## --- Data selection (numerical) ---

In [27]:
df.iloc[0:151]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
4,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,Dratini,Dragon,NaN,41,64,45,50,50,50,1,False
147,148,Dragonair,Dragon,NaN,61,84,65,70,70,70,1,False
148,149,Dragonite,Dragon,Flying,91,134,95,100,100,80,1,False
149,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True
150,151,Mew,Psychic,NaN,100,100,100,100,100,100,1,False

In [28]:
df.iloc[152:251]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
152,153,Bayleef,Grass,NaN,60,62,80,63,80,60,2,False
153,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False
154,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
155,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
156,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...
246,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False
247,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False
248,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True
249,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
250,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False

In [29]:
df.iloc[149,1]

'Mewtwo'

## --- Data selection (string) ---

In [30]:
df.loc[(df['Type 1'] == 'Psychic') & (df['Generation'] == 1)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
62,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
63,64,Kadabra,Psychic,NaN,40,35,30,120,70,105,1,False
64,65,Alakazam,Psychic,NaN,55,50,45,135,95,120,1,False
95,96,Drowzee,Psychic,NaN,60,48,45,43,90,42,1,False
96,97,Hypno,Psychic,NaN,85,73,70,73,115,67,1,False
121,122,Mr. Mime,Psychic,NaN,40,45,65,100,120,90,1,False
149,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True
150,151,Mew,Psychic,NaN,100,100,100,100,100,100,1,False

## --- Row iteration ---

In [31]:
for index, row in df.iterrows():
    print(row['#'], row['Name'])

1 Bulbasaur
2 Ivysaur
3 Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 Squirtle
8 Wartortle
9 Blastoise
10 Caterpie
11 Metapod
12 Butterfree
13 Weedle
14 Kakuna
15 Beedrill
16 Pidgey
17 Pidgeotto
18 Pidgeot
19 Rattata
20 Raticate
21 Spearow
22 Fearow
23 Ekans
24 Arbok
25 Pikachu
26 Raichu
27 Sandshrew
28 Sandslash
29 Nidoran (Female)
30 Nidorina
31 Nidoqueen
32 Nidoran (Male)
33 Nidorino
34 Nidoking
35 Clefairy
36 Clefable
37 Vulpix
38 Ninetales
39 Jigglypuff
40 Wigglytuff
41 Zubat
42 Golbat
43 Oddish
44 Gloom
45 Vileplume
46 Paras
47 Parasect
48 Venonat
49 Venomoth
50 Diglett
51 Dugtrio
52 Meowth
53 Persian
54 Psyduck
55 Golduck
56 Mankey
57 Primeape
58 Growlithe
59 Arcanine
60 Poliwag
61 Poliwhirl
62 Poliwrath
63 Abra
64 Kadabra
65 Alakazam
66 Machop
67 Machoke
68 Machamp
69 Bellsprout
70 Weepinbell
71 Victreebel
72 Tentacool
73 Tentacruel
74 Geodude
75 Graveler
76 Golem
77 Ponyta
78 Rapidash
79 Slowpoke
80 Slowbro
81 Magnemite
82 Magneton
83 Farfetch'd
84 Doduo
85 Dodrio
86 Seel
87 Dewgong
88 Grimer
89 Muk
90 Shellder
91 Cloyster
92 Gastly
93 Haunter
94 Gengar
95 Onix
96 Drowzee
97 Hypno
98 Krabby
99 Kingler
100 Voltorb
101 Electrode
102 Exeggcute
103 Exeggutor
104 Cubone
105 Marowak
106 Hitmonlee
107 Hitmonchan
108 Lickitung
109 Koffing
110 Weezing
111 Rhyhorn
112 Rhydon
113 Chansey
114 Tangela
115 Kangaskhan
116 Horsea
117 Seadra
118 Goldeen
119 Seaking
120 Staryu
121 Starmie
122 Mr. Mime
123 Scyther
124 Jynx
125 Electabuzz
126 Magmar
127 Pinsir
128 Tauros
129 Magikarp
130 Gyarados
131 Lapras
132 Ditto
133 Eevee
134 Vaporeon
135 Jolteon
136 Flareon
137 Porygon
138 Omanyte
139 Omastar
140 Kabuto
141 Kabutops
142 Aerodactyl
143 Snorlax
144 Articuno
145 Zapdos
146 Moltres
147 Dratini
148 Dragonair
149 Dragonite
150 Mewtwo
151 Mew
152 Chikorita
153 Bayleef
154 Meganium
155 Cyndaquil
156 Quilava
157 Typhlosion
158 Totodile
159 Croconaw
160 Feraligatr
161 Sentret
162 Furret
163 Hoothoot
164 Noctowl
165 Ledyba
166 Ledian
167 Spinarak
168 Ariados
169 Crobat
170 Chinchou
171 Lanturn
172 Pichu
173 Cleffa
174 Igglybuff
175 Togepi
176 Togetic
177 Natu
178 Xatu
179 Mareep
180 Flaaffy
181 Ampharos
182 Bellossom
183 Marill
184 Azumarill
185 Sudowoodo
186 Politoed
187 Hoppip
188 Skiploom
189 Jumpluff
190 Aipom
191 Sunkern
192 Sunflora
193 Yanma
194 Wooper
195 Quagsire
196 Espeon
197 Umbreon
198 Murkrow
199 Slowking
200 Misdreavus
201 Unown
202 Wobbuffet
203 Girafarig
204 Pineco
205 Forretress
206 Dunsparce
207 Gligar
208 Steelix
209 Snubbull
210 Granbull
211 Qwilfish
212 Scizor
213 Shuckle
214 Heracross
215 Sneasel
216 Teddiursa
217 Ursaring
218 Slugma
219 Magcargo
220 Swinub
221 Piloswine
222 Corsola
223 Remoraid
224 Octillery
225 Delibird
226 Mantine
227 Skarmory
228 Houndour
229 Houndoom
230 Kingdra
231 Phanpy
232 Donphan
233 Porygon2
234 Stantler
235 Smeargle
236 Tyrogue
237 Hitmontop
238 Smoochum
239 Elekid
240 Magby
241 Miltank
242 Blissey
243 Raikou
244 Entei
245 Suicune
246 Larvitar
247 Pupitar
248 Tyranitar
249 Lugia
250 Ho-oh
251 Celebi

## --- Describe ---

In [32]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000
mean,126.000000,66.749004,70.840637,68.729084,66.007968,68.458167,65.936255,1.398406
std,72.601653,29.797261,27.361844,30.399841,27.323688,27.452236,27.143101,0.490548
min,1.000000,10.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.000000
25%,63.500000,49.000000,50.000000,49.500000,45.000000,50.000000,45.000000,1.000000
50%,126.000000,65.000000,70.000000,65.000000,65.000000,65.000000,65.000000,1.000000
75%,188.500000,80.000000,90.000000,85.000000,85.000000,85.000000,85.000000,2.000000
max,251.000000,255.000000,134.000000,230.000000,154.000000,230.000000,140.000000,2.000000

## --- Sorting values ---

In [33]:
df.sort_values(['Sp. Atk', 'HP'], ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
149,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True
64,65,Alakazam,Psychic,NaN,55,50,45,135,95,120,1,False
195,196,Espeon,Psychic,NaN,65,65,60,130,95,110,2,False
93,94,Gengar,Ghost,Poison,60,65,60,130,75,110,1,False
102,103,Exeggutor,Grass,Psychic,95,95,85,125,65,55,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
26,27,Sandshrew,Ground,NaN,50,75,85,20,30,40,1,False
9,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False
12,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
128,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
212,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False

## --- Adding columns ---

In [34]:
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
4,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False,410
247,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False,600
248,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True,680
249,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
250,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False,600

In [35]:
# This is the same as above. The syntax [:,4:10] means you're adding all the columbs between the 4th to the 9th column.
# The sum() at the end determines if you're adding vertically or horizonally:
# 0 is vertically and 1 is horizontally.

df['Total'] = df.iloc[:,4:10].sum(axis=1)
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
4,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False,410
247,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False,600
248,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True,680
249,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
250,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False,600

## --- Column rearranging ---

In [36]:
cols = list(df.columns.values)
cols_rearrange_df = df[cols[0:4] + [cols[-1]] + cols[4:12]]
cols_rearrange_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,247,Pupitar,Rock,Ground,410,70,84,70,65,70,51,2,False
247,248,Tyranitar,Rock,Dark,600,100,134,110,95,100,61,2,False
248,249,Lugia,Psychic,Flying,680,106,90,130,90,154,110,2,True
249,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
250,251,Celebi,Psychic,Grass,600,100,100,100,100,100,100,2,False

In [37]:
index_reset = df.loc[(df['Type 1'] == 'Psychic') | (df['Type 2'] == 'Flying') & (df['Generation'] == 2)]
index_reset.reset_index(drop=True,inplace=True)
index_reset

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False,310
1,64,Kadabra,Psychic,NaN,40,35,30,120,70,105,1,False,400
2,65,Alakazam,Psychic,NaN,55,50,45,135,95,120,1,False,500
3,96,Drowzee,Psychic,NaN,60,48,45,43,90,42,1,False,328
4,97,Hypno,Psychic,NaN,85,73,70,73,115,67,1,False,483
5,122,Mr. Mime,Psychic,NaN,40,45,65,100,120,90,1,False,460
6,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True,680
7,151,Mew,Psychic,NaN,100,100,100,100,100,100,1,False,600
8,163,Hoothoot,Normal,Flying,60,30,30,36,56,50,2,False,262
9,164,Noctowl,Normal,Flying,100,50,50,76,96,70,2,False,442
10,165,Ledyba,Bug,Flying,40,20,30,40,80,55,2,False,265
11,166,Ledian,Bug,Flying,55,35,50,55,110,85,2,False,390
12,169,Crobat,Poison,Flying,85,90,80,70,80,130,2,False,535
13,176,Togetic,Normal,Flying,55,40,85,80,105,40,2,False,405
14,177,Natu,Psychic,Flying,40,50,45,70,45,70,2,False,320
15,178,Xatu,Psychic,Flying,65,75,70,95,70,95,2,False,470
16,187,Hoppip,Grass,Flying,35,35,40,35,55,50,2,False,250
17,188,Skiploom,Grass,Flying,55,45,50,45,65,80,2,False,340
18,189,Jumpluff,Grass,Flying,75,55,70,55,95,110,2,False,460
19,193,Yanma,Bug,Flying,65,65,45,75,45,95,2,False,390
20,196,Espeon,Psychic,NaN,65,65,60,130,95,110,2,False,525
21,198,Murkrow,Dark,Flying,60,85,42,85,42,91,2,False,405
22,201,Unown,Psychic,NaN,48,72,48,72,48,48,2,False,336
23,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False,405
24,207,Gligar,Ground,Flying,65,75,105,35,65,85,2,False,430
25,225,Delibird,Ice,Flying,45,55,45,65,45,75,2,False,330
26,226,Mantine,Water,Flying,65,40,70,80,140,70,2,False,465
27,227,Skarmory,Steel,Flying,65,80,140,40,70,70,2,False,465
28,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True,680
29,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
30,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False,600

## --- String search ---

In [40]:
df.loc[df['Name'].str.contains('chu')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
24,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,320
25,26,Raichu,Electric,NaN,60,90,55,90,80,110,1,False,485
171,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,205
237,238,Smoochum,Ice,Psychic,45,30,15,85,65,65,2,False,305

In [45]:
df.loc[~df['Name'].str.contains('a')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
6,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False,314
11,12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False,395
12,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False,195
14,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False,395
15,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False,540
243,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,580
244,245,Suicune,Water,NaN,100,75,115,90,115,85,2,True,580
249,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
250,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False,600

## --- Regex ---

In [51]:
# The flag 're.I' is ignore, which allows us to look for all names regardless of its cases.

import re

df.loc[df['Type 1'].str.contains('dark|steel', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
196,197,Umbreon,Dark,NaN,95,65,110,60,130,65,2,False,525
197,198,Murkrow,Dark,Flying,60,85,42,85,42,91,2,False,405
207,208,Steelix,Steel,Ground,75,85,200,55,65,30,2,False,510
214,215,Sneasel,Dark,Ice,55,95,55,35,75,115,2,False,430
226,227,Skarmory,Steel,Flying,65,80,140,40,70,70,2,False,465
227,228,Houndour,Dark,Fire,45,60,30,80,50,65,2,False,330
228,229,Houndoom,Dark,Fire,75,90,50,110,80,95,2,False,500

In [59]:
import re

df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
15,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
16,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
17,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
24,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,320
126,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False,500
171,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,205
203,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290
220,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450

## --- Value changes ---

In [65]:
type_changer = df.loc[df['Type 1'] == 'Steel', 'Type 1'] = 'Metal'
df.tail(50)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
201,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False,405
202,203,Girafarig,Normal,Psychic,70,80,65,90,65,85,2,False,455
203,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290
204,205,Forretress,Bug,Steel,75,90,140,60,60,40,2,False,465
205,206,Dunsparce,Normal,NaN,100,70,70,65,65,45,2,False,415
206,207,Gligar,Ground,Flying,65,75,105,35,65,85,2,False,430
207,208,Steelix,Metal,Ground,75,85,200,55,65,30,2,False,510
208,209,Snubbull,Normal,NaN,60,80,50,40,40,30,2,False,300
209,210,Granbull,Normal,NaN,90,120,75,60,60,45,2,False,450
210,211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,False,430
211,212,Scizor,Bug,Steel,70,130,100,55,80,65,2,False,500
212,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False,505
213,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False,500
214,215,Sneasel,Dark,Ice,55,95,55,35,75,115,2,False,430
215,216,Teddiursa,Normal,NaN,60,80,50,50,50,40,2,False,330
216,217,Ursaring,Normal,NaN,90,130,75,75,75,55,2,False,500
217,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False,250
218,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False,410
219,220,Swinub,Ice,Ground,50,50,40,30,30,50,2,False,250
220,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
221,222,Corsola,Water,Rock,55,55,85,65,85,35,2,False,380
222,223,Remoraid,Water,NaN,35,65,35,65,35,65,2,False,300
223,224,Octillery,Water,NaN,75,105,75,105,75,45,2,False,480
224,225,Delibird,Ice,Flying,45,55,45,65,45,75,2,False,330
225,226,Mantine,Water,Flying,65,40,70,80,140,70,2,False,465
226,227,Skarmory,Metal,Flying,65,80,140,40,70,70,2,False,465
227,228,Houndour,Dark,Fire,45,60,30,80,50,65,2,False,330
228,229,Houndoom,Dark,Fire,75,90,50,110,80,95,2,False,500
229,230,Kingdra,Water,Dragon,75,95,95,95,95,85,2,False,540
230,231,Phanpy,Ground,NaN,90,60,60,40,40,40,2,False,330
231,232,Donphan,Ground,NaN,90,120,120,60,60,50,2,False,500
232,233,Porygon2,Normal,NaN,85,80,90,105,95,60,2,False,515
233,234,Stantler,Normal,NaN,73,95,62,85,65,85,2,False,465
234,235,Smeargle,Normal,NaN,55,20,35,20,45,75,2,False,250
235,236,Tyrogue,Fighting,NaN,35,35,35,35,35,35,2,False,210
236,237,Hitmontop,Fighting,NaN,50,95,95,35,110,70,2,False,455
237,238,Smoochum,Ice,Psychic,45,30,15,85,65,65,2,False,305
238,239,Elekid,Electric,NaN,45,63,37,65,55,95,2,False,360
239,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False,365
240,241,Miltank,Normal,NaN,95,80,105,40,70,100,2,False,490
241,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False,540
242,243,Raikou,Electric,NaN,90,85,75,115,100,115,2,True,580
243,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,580
244,245,Suicune,Water,NaN,100,75,115,90,115,85,2,True,580
245,246,Larvitar,Rock,Ground,50,64,50,45,50,41,2,False,300
246,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False,410
247,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False,600
248,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True,680
249,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
250,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False,600

In [66]:
type_changer = df.loc[df['Type 1'] == 'Metal', 'Type 1'] = 'Steel'
df.tail(50)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
201,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False,405
202,203,Girafarig,Normal,Psychic,70,80,65,90,65,85,2,False,455
203,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290
204,205,Forretress,Bug,Steel,75,90,140,60,60,40,2,False,465
205,206,Dunsparce,Normal,NaN,100,70,70,65,65,45,2,False,415
206,207,Gligar,Ground,Flying,65,75,105,35,65,85,2,False,430
207,208,Steelix,Steel,Ground,75,85,200,55,65,30,2,False,510
208,209,Snubbull,Normal,NaN,60,80,50,40,40,30,2,False,300
209,210,Granbull,Normal,NaN,90,120,75,60,60,45,2,False,450
210,211,Qwilfish,Water,Poison,65,95,75,55,55,85,2,False,430
211,212,Scizor,Bug,Steel,70,130,100,55,80,65,2,False,500
212,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False,505
213,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False,500
214,215,Sneasel,Dark,Ice,55,95,55,35,75,115,2,False,430
215,216,Teddiursa,Normal,NaN,60,80,50,50,50,40,2,False,330
216,217,Ursaring,Normal,NaN,90,130,75,75,75,55,2,False,500
217,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False,250
218,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False,410
219,220,Swinub,Ice,Ground,50,50,40,30,30,50,2,False,250
220,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
221,222,Corsola,Water,Rock,55,55,85,65,85,35,2,False,380
222,223,Remoraid,Water,NaN,35,65,35,65,35,65,2,False,300
223,224,Octillery,Water,NaN,75,105,75,105,75,45,2,False,480
224,225,Delibird,Ice,Flying,45,55,45,65,45,75,2,False,330
225,226,Mantine,Water,Flying,65,40,70,80,140,70,2,False,465
226,227,Skarmory,Steel,Flying,65,80,140,40,70,70,2,False,465
227,228,Houndour,Dark,Fire,45,60,30,80,50,65,2,False,330
228,229,Houndoom,Dark,Fire,75,90,50,110,80,95,2,False,500
229,230,Kingdra,Water,Dragon,75,95,95,95,95,85,2,False,540
230,231,Phanpy,Ground,NaN,90,60,60,40,40,40,2,False,330
231,232,Donphan,Ground,NaN,90,120,120,60,60,50,2,False,500
232,233,Porygon2,Normal,NaN,85,80,90,105,95,60,2,False,515
233,234,Stantler,Normal,NaN,73,95,62,85,65,85,2,False,465
234,235,Smeargle,Normal,NaN,55,20,35,20,45,75,2,False,250
235,236,Tyrogue,Fighting,NaN,35,35,35,35,35,35,2,False,210
236,237,Hitmontop,Fighting,NaN,50,95,95,35,110,70,2,False,455
237,238,Smoochum,Ice,Psychic,45,30,15,85,65,65,2,False,305
238,239,Elekid,Electric,NaN,45,63,37,65,55,95,2,False,360
239,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False,365
240,241,Miltank,Normal,NaN,95,80,105,40,70,100,2,False,490
241,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False,540
242,243,Raikou,Electric,NaN,90,85,75,115,100,115,2,True,580
243,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,580
244,245,Suicune,Water,NaN,100,75,115,90,115,85,2,True,580
245,246,Larvitar,Rock,Ground,50,64,50,45,50,41,2,False,300
246,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False,410
247,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False,600
248,249,Lugia,Psychic,Flying,106,90,130,90,154,110,2,True,680
249,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
250,251,Celebi,Psychic,Grass,100,100,100,100,100,100,2,False,600

## --- Statistics ---

In [97]:
df.groupby(['Type 1']).mean().sort_values('HP', ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,
Normal,128.022727,79.409091,64.477273,54.818182,55.113636,63.386364,61.363636,1.454545,0.000000,378.568182
Psychic,150.800000,75.000000,64.400000,64.733333,94.666667,87.000000,87.333333,1.466667,0.133333,473.133333
Steel,217.500000,70.000000,82.500000,170.000000,47.500000,67.500000,50.000000,2.000000,0.000000,487.500000
Water,129.260870,69.173913,69.413043,75.543478,66.173913,69.891304,63.456522,1.391304,0.021739,413.652174
Dark,213.400000,66.000000,79.000000,57.400000,74.000000,75.400000,86.200000,2.000000,0.000000,438.000000
Poison,58.933333,65.866667,75.466667,67.866667,58.000000,62.866667,63.533333,1.066667,0.000000,393.600000
Ice,195.333333,65.833333,61.666667,52.500000,75.000000,70.000000,70.000000,1.666667,0.166667,395.000000
Fire,120.450000,64.850000,80.850000,65.100000,84.200000,76.200000,78.800000,1.400000,0.150000,450.000000
Ground,114.363636,64.545455,82.727273,88.636364,40.909091,51.818182,58.181818,1.272727,0.000000,386.818182
Dragon,148.000000,64.333333,94.000000,68.333333,73.333333,73.333333,66.666667,1.000000,0.000000,440.000000
Grass,107.380952,62.380952,64.809524,67.619048,76.666667,68.809524,55.238095,1.428571,0.000000,395.523810
Rock,149.692308,59.615385,86.307692,102.692308,60.000000,60.384615,54.461538,1.307692,0.000000,423.461538
Fighting,111.111111,58.888889,94.444444,61.888889,42.777778,73.333333,63.111111,1.222222,0.000000,394.444444
Electric,134.266667,57.333333,61.066667,59.266667,86.333333,69.666667,86.333333,1.400000,0.133333,420.000000
Bug,110.090909,55.909091,66.136364,70.681818,47.272727,68.181818,54.545455,1.454545,0.000000,362.727273
Ghost,119.750000,48.750000,52.500000,48.750000,107.500000,62.500000,92.500000,1.250000,0.000000,412.500000

In [99]:
df.groupby(['Type 1']).count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
Type 1,,,,,,,,,,,,
Bug,22,22,18,22,22,22,22,22,22,22,22,22
Dark,5,5,4,5,5,5,5,5,5,5,5,5
Dragon,3,3,1,3,3,3,3,3,3,3,3,3
Electric,15,15,3,15,15,15,15,15,15,15,15,15
Fighting,9,9,0,9,9,9,9,9,9,9,9,9
Fire,20,20,4,20,20,20,20,20,20,20,20,20
Ghost,4,4,3,4,4,4,4,4,4,4,4,4
Grass,21,21,14,21,21,21,21,21,21,21,21,21
Ground,11,11,3,11,11,11,11,11,11,11,11,11
Ice,6,6,6,6,6,6,6,6,6,6,6,6
Normal,44,44,12,44,44,44,44,44,44,44,44,44
Poison,15,15,5,15,15,15,15,15,15,15,15,15
Psychic,15,15,4,15,15,15,15,15,15,15,15,15
Rock,13,13,12,13,13,13,13,13,13,13,13,13
Steel,2,2,2,2,2,2,2,2,2,2,2,2
Water,46,46,19,46,46,46,46,46,46,46,46,46

In [103]:
df.groupby(['Type 1', 'Type 2']).count()['#']

Type 1    Type 2
Bug       Fighting     1
          Flying       5
          Grass        2
          Poison       7
          Rock         1
          Steel        2
Dark      Fire         2
          Flying       1
          Ice          1
Dragon    Flying       1
Electric  Flying       1
          Steel        2
Fire      Flying       3
          Rock         1
Ghost     Poison       3
Grass     Flying       3
          Poison       9
          Psychic      2
Ground    Flying       1
          Rock         2
Ice       Flying       2
          Ground       2
          Psychic      2
Normal    Flying      11
          Psychic      1
Poison    Flying       3
          Ground       2
Psychic   Flying       3
          Grass        1
Rock      Dark         1
          Flying       1
          Ground       6
          Water        4
Steel     Flying       1
          Ground       1
Water     Dragon       1
          Electric     2
          Fighting     1
          Flying       2
          Ground       2
          Ice          3
          Poison       3
          Psychic      4
          Rock         1
Name: #, dtype: int64

## --- Special thanks ---
https://www.youtube.com/watch?v=vmEHCJofslg